_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 2
                - 13
                - 14
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.4
            "8":
                - 1
                - 5
            "12": 0.19.4
            "13": darwin-arm64
DROPOUT_RATE:
    value: 0.3459760722269364
LEARNING_RATE:
    value: 0.0667343518923268
N_DENSE_1:
    value: 32
N_DENSE_2:
    value: 16
REGULARIZATION_RATE:
    value: 0.09468152452108013
