_wandb:
    value:
        cli_version: 0.19.4
        m:
            - "1": epoch/epoch
              "6":
                - 3
              "7": []
        python_version: 3.11.11
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 2
                - 7
                - 13
                - 14
                - 16
                - 23
                - 38
                - 39
                - 55
            "4": 3.11.11
            "5": 0.19.4
            "8":
                - 1
                - 5
            "12": 0.19.4
            "13": darwin-arm64
BATCH_SIZE:
    value: 128
DROPOUT_RATE:
    value: 0.2647709010473697
IM_SIZE:
    value: 224
KERNEL_SIZE:
    value: 3
LEARNING_RATE:
    value: 0.0777055846847652
N_DENSE_1:
    value: 128
N_DENSE_2:
    value: 32
N_EPOCHS:
    value: 10
N_FILTERS:
    value: 6
N_STRIDES:
    value: 1
POOL_SIZE:
    value: 2
REGULARIZATION_RATE:
    value: 0.02484577717720783
