_wandb:
    value:
        cli_version: 0.19.5
        m:
            - "1": epoch/top_k_accuracy
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/epoch
              "6":
                - 3
              "7": []
            - "1": epoch/accuracy
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/val_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/val_accuracy
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/learning_rate
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/val_top_k_accuracy
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.11.11
        t:
            "1":
                - 2
                - 3
                - 5
                - 11
                - 49
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 11
                - 49
                - 53
                - 55
            "3":
                - 2
                - 7
                - 13
                - 23
                - 38
                - 39
                - 55
            "4": 3.11.11
            "5": 0.19.5
            "6": 4.48.2
            "8":
                - 1
                - 2
                - 5
            "12": 0.19.5
            "13": darwin-arm64
        visualize:
            Confusion Matrix:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: Confusion Matrix_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
