_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
                - 80
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
                - 80
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.4
            "8":
                - 1
                - 5
            "12": 0.19.4
            "13": darwin-arm64
